version: '3.1'

services:
  db:
    image: mysql:8.0.28
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
    volumes:
    - ./initdb.d:/docker-entrypoint-initdb.d